import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { exportFountain, parseFountain } from '../fountainExport';
import type { ScreenplayElement } from '@/types/screenplay';

/**
 * Feature: draftkit-screenwriter
 * Property 2: Fountain Export Round-Trip
 *
 * For any valid ScreenplayElement[] avoiding ambiguous Fountain edge cases,
 * exporting to Fountain format via exportFountain and then parsing back
 * via parseFountain SHALL produce an array equivalent to the original.
 *
 * **Validates: Requirements 12.6**
 */
describe('Property 2: Fountain Export Round-Trip', () => {
  const SCENE_PREFIXES = ['INT.', 'EXT.', 'INT./EXT.', 'EXT./INT.', 'I/E.', 'E/I.'];

  // Generate printable ASCII text without newlines, safe for Fountain
  const safeFountainTextArb = fc
    .stringMatching(/^[a-z][a-z0-9 ,.!?;:'-]{0,80}$/)
    .filter(s => s.trim().length > 0);

  // For CHARACTER: must be all uppercase letters
  const characterNameArb = fc
    .stringMatching(/^[A-Z][A-Z ]{1,20}$/)
    .filter(s => {
      const trimmed = s.trim();
      if (trimmed.length < 2) return false;
      if (!/[A-Z]/.test(trimmed)) return false;
      if (SCENE_PREFIXES.some(p => trimmed.startsWith(p))) return false;
      return true;
    });

  // For SCENE_HEADING: use text that doesn't start with special chars
  const sceneHeadingTextArb = safeFountainTextArb;

  // For DIALOGUE: lowercase/mixed case text
  const dialogueTextArb = safeFountainTextArb;

  // For PARENTHETICAL: text without parens (export adds them)
  const parentheticalTextArb = safeFountainTextArb.filter(s => !s.includes('(') && !s.includes(')'));

  // For TRANSITION: any safe text
  const transitionTextArb = safeFountainTextArb;

  // For ACTION: lowercase/mixed case text
  const actionTextArb = safeFountainTextArb;

  // Build structured blocks to ensure valid Fountain structure
  type Block =
    | { kind: 'scene'; text: string }
    | { kind: 'action'; text: string }
    | { kind: 'dialogue'; character: string; lines: { type: 'DIALOGUE' | 'PARENTHETICAL'; text: string }[] }
    | { kind: 'transition'; text: string };

  const dialogueLineArb = fc.oneof(
    dialogueTextArb.map(t => ({ type: 'DIALOGUE' as const, text: t })),
    parentheticalTextArb.map(t => ({ type: 'PARENTHETICAL' as const, text: `(${t})` })),
  );

  const blockArb: fc.Arbitrary<Block> = fc.oneof(
    sceneHeadingTextArb.map(text => ({ kind: 'scene' as const, text })),
    actionTextArb.map(text => ({ kind: 'action' as const, text })),
    fc.record({
      kind: fc.constant('dialogue' as const),
      character: characterNameArb,
      lines: fc.array(dialogueLineArb, { minLength: 1, maxLength: 3 }),
    }),
    transitionTextArb.map(text => ({ kind: 'transition' as const, text })),
  );

  const blocksArb = fc.array(blockArb, { minLength: 0, maxLength: 15 });

  function blocksToElements(blocks: Block[]): ScreenplayElement[] {
    const elements: ScreenplayElement[] = [];
    let order = 0;
    for (const block of blocks) {
      switch (block.kind) {
        case 'scene':
          elements.push({ id: `ft-${order}`, type: 'SCENE_HEADING', text: block.text, order: order++ });
          break;
        case 'action':
          elements.push({ id: `ft-${order}`, type: 'ACTION', text: block.text, order: order++ });
          break;
        case 'dialogue':
          elements.push({ id: `ft-${order}`, type: 'CHARACTER', text: block.character, order: order++ });
          for (const line of block.lines) {
            elements.push({ id: `ft-${order}`, type: line.type, text: line.text, order: order++ });
          }
          break;
        case 'transition':
          elements.push({ id: `ft-${order}`, type: 'TRANSITION', text: block.text, order: order++ });
          break;
      }
    }
    return elements;
  }

  it('elements → Fountain → elements produces equivalent array (ignoring ids)', () => {
    fc.assert(
      fc.property(blocksArb, (blocks) => {
        const elements = blocksToElements(blocks);
        const fountain = exportFountain(elements);
        const result = parseFountain(fountain);

        // Compare type, text, and order (ids are regenerated by parser)
        const normalize = (els: ScreenplayElement[]) =>
          els.map(el => ({ type: el.type, text: el.text, order: el.order }));

        expect(normalize(result)).toEqual(normalize(elements));
      }),
      { numRuns: 100 },
    );
  });
});
